name: BluffParkDrone
favicon: null
layout_spectrum: 0.58794
typography_spectrum: 0.5086368520278484
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#36353b'
    - '#948373'
    - '#9ab3c9'
    - '#188c95'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.3456632050219923
purpose: []
